### DISCUSSION TITLE
Schema / Envelope for use with Step Functions

### DISCUSSION THREAD

**Discussion by jsvandeven-ws** [aws-powertools/powertools-lambda-typescript#2864] [Q&A] [answered]
Looking at the [built in schemas](https://docs.powertools.aws.dev/lambda/typescript/latest/utilities/parser/#built-in-schemas) for the parser, I don't see one for use with step functions. Are any of the available parsers suitable for use with step function invocation of lambdas?

**Comment by dreamorosi** [comment]
Hi @jsvandeven-ws, could you share an example of a payload you're referring to, and a link to its documentation?

**Reply by jsvandeven-ws** [reply]
Hmm not sure if this helps, but for example I have a state machine defined in a cloud formation template as below:

```yaml
  StepFunction:
    Type: AWS::Serverless::StateMachine
    Properties:
      Role: !GetAtt StepFunctionRole.Arn
      Definition:
        StartAt: ManageStackSet
        States:
          ManageStackSet:
            Type: Task
            Resource: !GetAtt ManageStackSet.Arn
            InputPath: $
            Parameters:
              StackSetNamePrefix: !Ref StackSetNamePrefix
              AccountPrefix.$: $.accountPrefix
              Accounts.$: $.accounts
              ExecutionId.$: $$.Execution.Name
            ResultPath: $.Result
            OutputPath: $
            Next: WaitForStackSet
```

Is there a schema that would match the event passed to the `ManageStackSet` lambda function? It looks like state machine states have a pretty unique payload in that you define the shape with the `InputPath`, if I'm understanding things correctly.
