### ISSUE TITLE
Maintenance: fix beta docs publishing

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1490]
### Summary

After making the `v1.9.0` release I had to remove the portion of the workflow that publishes the docs to the beta website because it kept making the workflow fail preventing the docs to be published. Here's a [reference of the failed workflow](https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/5224311620).

The error is similar to an error that we have already seen in the past, but that it appears to not be fixed yet.

We should troubleshoot the issue & try to fix it for good.

### Why is this needed?

So that we can keep publishing the docs to the new beta destination.

```yml
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # v2.0.0
  with:
    aws-region: us-east-1
    role-to-assume: ${{ secrets.AWS_DOCS_ROLE_ARN }}
- name: Copy API Docs
   run: |
     cp -r api site/
- name: Deploy Docs (Version)
   env:
     VERSION: ${{ inputs.version }}
     ALIAS: ${{ inputs.alias }}
   run: |
     aws s3 sync \
     site/ \
     s3://${{ secrets.AWS_DOCS_BUCKET }}/lambda-typescript/${{ env.VERSION }}/
- name: Deploy Docs (Alias)
     env:
       VERSION: ${{ inputs.version }}
       ALIAS: ${{ inputs.alias }}
     run: |
       aws s3 sync \
       site/ \
       s3://${{ secrets.AWS_DOCS_BUCKET }}/lambda-typescript/${{ env.ALIAS }}/
```

### Which area does this relate to?

Automation

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/), and [.NET](https://github.com/awslabs/aws-lambda-powertools-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.
