### ISSUE TITLE
Maintenance: run e2e tests in parallel

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1512]
### Summary

While we run e2e tests in a matrix: 

```yaml
    strategy:
      matrix:
        package: [logger, metrics, tracer, parameters]
        version: [14, 16, 18]
      fail-fast: false
```

it would be great to also be able to execute these tests during development. 

### Why is this needed?

To reduce feedback cycle time for e2e tests during development. 

### Which area does this relate to?

Automation

### Solution

@dreamorosi already opened [a discussion](https://github.com/npm/feedback/discussions/781), and the pointers to RFCs. I don't have a solution yet, so any recommendation and contribution is appreciated. 

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.
