### ISSUE TITLE
Docs: typo aws::region in serverless framework and terraform

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1706]
### What were you searching in the docs?

The example of powertools with serverless framework has incorrect syntax for aws region variable: 

```yaml
functions:
  hello:
    handler: lambda_function.lambda_handler
    layers:
      - arn:aws:lambda:${aws::region}:094274105915:layer:AWSLambdaPowertoolsTypeScript:19
```

Keen in mind that we need to update the script in the workflow, so we can replace increment the layer version in the docs during release.

https://github.com/aws-powertools/powertools-lambda-typescript/blob/06815118da45973d69b2c57124cf0ccd5255c88a/.github/scripts/update_layer_arn.sh#L59

### Is this related to an existing documentation section?

Getting started

### How can we improve?

```Markdown
Review all the `aws::region` variables, including terraform.
```

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.
