### ISSUE TITLE
Maintenance: add groups for Dependabot

### ISSUE THREAD

**Issue by am29d** [aws-powertools/powertools-lambda-typescript#1883]
### Summary

To reduce daily overload of dependabot, we should use groups to combine multiple PR for similar groups: 

* actions
* @aws-sdk

### Why is this needed?

This will reduce the number of open PRS with small changes.

### Which area does this relate to?

Automation

### Solution

Use `groups` section for dependabot yaml
```yaml
# `dependabot.yml` file using the `update-types` option to group updates.
# Any packages matching the pattern @angular* where the highest resolvable
# version is minor or patch will be grouped together.
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
        - "@angular*"
        update-types:
        - "minor"
        - "patch"
```

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.
