### ISSUE TITLE
Maintenance: Refactor artifact name strategy for parallel uploads

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2042]
### Summary

GitHub `actions/upload-artifact` v4 has a racing condition when uploading artifacts with the same artifact name in parallel.

For example, our Lambda Layer CDK artifacts are uploaded on a per region deploy in parallel using the [a static output name.](https://github.com/aws-powertools/powertools-lambda-typescript/blob/ff70f226432123638adb09f03e6892d6b399d3c9/.github/workflows/reusable_deploy_layer_stack.yml#L96)

While in our repo the workflow ran successfully, the Python version of Powertools was not as lucky and their [release](https://github.com/aws-powertools/powertools-lambda-python/actions/runs/7843824086) failed partially (rerunning the failed jobs serves as a short term workaround).

<img width="804" alt="image" src="https://github.com/aws-powertools/powertools-lambda-typescript/assets/7353869/cc2b8f7a-c85f-4216-9517-4ba657484754">

Related to aws-powertools/powertools-lambda-python#3748

### Why is this needed?

N/A

### Solution

Since it's a race condition on upload, we need a dynamic artifact name e.g., one per region. Then [merge these artifacts on download](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/workflows/reusable_deploy_layer_stack.yml#L78-L81).

> Updating to a dynamic name

```yaml
      - name: Download CDK layer artifact
        uses: actions/download-artifact@eaceaf801fd36c7dee90939fad912460b18a1ffe # v4.1.2
        with:
          name: cdk-layer-stack
          path: cdk-layer-stack/
          merge-multiple: true
```

> Downloading all artifacts for all regions

```yaml
      - name: Save Layer ARN artifact
        if: ${{ inputs.stage == 'PROD' }}
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: cdk-layer-stack-{{ matrix.region }}
          path: ./layer/cdk-layer-stack/* # NOTE: upload-artifact does not inherit working-directory setting.
          if-no-files-found: error
          retention-days: 1
          overwrite: true   # still needed to allow failed retries
```

Or using https://github.com/actions/upload-artifact/pull/505

We'll need a testing environment to create a parallel job to test this out.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.
