### ISSUE TITLE
Docs: Add llms.txt to documentation

### ISSUE THREAD

**Issue by hjgraca** [aws-powertools/powertools-lambda-typescript#3952]
### What were you searching in the docs?

Add support for llms.txt and llms-full.txt in Powertools for AWS documentation site
This will allow developers to add Powertools for AWS Lambda documentation context to their tools, IDEs, etc

### How can we improve?

Add support for llms.txt and llms-full.txt in Powertools for AWS documentation site

llms.txt will contain the links to the sections defined on the yaml
llms-full.txt will contain all the markdown text of those pages

### Got a suggestion in mind?

```yaml
  - llmstxt:
      markdown_description: Powertools for AWS Lambda (TypeScript) is a developer toolkit to implement Serverless best practices and increase developer velocity. It provides a suite of utilities for AWS Lambda Functions that makes tracing with AWS X-Ray, structured logging and creating custom metrics asynchronously easier.
      full_output: llms-full.txt
      sections:
        Getting Started:
          - getting-started/installation.md
          - getting-started/usage-patterns.md
          - getting-started/typescript-settings.md
          - getting-started/lambda-layers.md
        Features:
          - features/index.md
          - features/tracer.md
          - features/logger.md
          - features/metrics.md
          - features/event-handler/appsync-events.md
          - features/parameters.md
          - features/idempotency.md
          - features/batch.md
          - features/jmespath.md
          - features/parser.md
          - features/validation.md
        Environment variables: 
          - environment-variables.md
        Upgrade guide: 
          - upgrade.md
        Processes:
          - roadmap.md
          - versioning.md
          - maintainers.md
          - contributing/setup.md
          - contributing/getting_started.md
          - contributing/conventions.md
          - contributing/testing.md
```

### Acknowledgment

- [x] I understand the final update might be different from my proposed suggestion, or refused.
